language: php

sudo: false

php:
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm

env:
    - VALIDATOR_VERSION="2.7.*"
    - VALIDATOR_VERSION="2.8.*"
    - VALIDATOR_VERSION="3.2.*"
    - VALIDATOR_VERSION="dev-master"

before_script:
    - mkdir -p build/logs
    - composer require symfony/validator:${VALIDATOR_VERSION} --prefer-dist --no-interaction --no-progress

script:
    - vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml
    - if [ "${TRAVIS_PHP_VERSION}" != 'hhvm' ] && [ "${TRAVIS_PHP_VERSION}" != 'nightly' ]; then travis_retry wget -q https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && travis_retry php coveralls.phar -v; fi

notifications:
    email:
        - antalaron@antalaron.hu

cache:
    directories:
        - $HOME/.composer/cache
